# Site settings
title: Tinned Fruit
subtitle: Good old-fashioned handcrafted web produce
email: james@tinnedfruit.com
description: >
  Tinned Fruit is inhabited by Jim Newbery,
  a web developer based in Edinburgh, UK.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://froots.github.io" # the base hostname & protocol for your site
twitter_username: froots101
github_username: froots
timezone: Europe/London

# Build settings
markdown: kramdown
highlighter: pygments
kramdown:
  input: GFM

# sass:
#   style: :compressed

# Default github pages settings
safe: true
lsi: false
source: .
