# Site settings
title: Tinned Fruit
subtitle: Good old-fashioned handcrafted web produce
author: Jim Newbery
email: james@tinnedfruit.com
description: >
  Tinned Fruit. Front-end web strategy and implementation consulting by Jim Newbery.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://tinnedfruit.com" # the base hostname & protocol for your site
twitter_username: froots101
github_username: froots
fb_id: 637816442
timezone: Europe/London
gtm_property: GTM-MWKCMM
ga_property: UA-376970-1
optimize_container: GTM-MMTJJL4
author_avatar: /images/main/avatar.jpg
author_about_url: /contact/
permalink: /articles/:categories/:title.html
paginate: 5
paginate_path: "/articles/:num/"

# Dependencies:

plugins:
  - jekyll-redirect-from
  - jekyll-paginate

whitelist:
  - jekyll-redirect-from
  - jekyll-paginate

# Build settings
markdown: kramdown
kramdown:
  input: GFM

sass:
  style: :compressed

# Default github pages settings
safe: true
lsi: false
source: .

# Custom stuff
webfont_version: 1

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

collections:
  testimonials:
    output: false
