safe:        false
auto:        true
server:      false
server_port: 4000

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    true
markdown:    maruku
permalink:   date

title:       Tinned Fruit
subtitle:    Good old-fashioned handcrafted web produce
description: Tinned Fruit is inhabited by Jim Newbery, a web developer based in Edinburgh, UK.
domain:      http://tinnedfruit.com
author:      Jim Newbery
email:       james@tinnedfruit.com

ftp_host:    tinnedfruit.com
# ftp_dir:      tinnedfruit.com
ftp_dir:     dev.tinnedfruit.com


maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  
  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style