# Site settings
title: Tinned Fruit
subtitle: Front-end leadership coaching and consulting by Jim Newbery.
author: Jim Newbery
email: james@tinnedfruit.com
description: >
  Front-end leadership coaching and consulting by Jim Newbery.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://tinnedfruit.com" # the base hostname & protocol for your site
twitter_username: froots101
github_username: froots
fb_id: 637816442
timezone: Europe/London
gtm_property: GTM-MWKCMM
ga_property: UA-376970-1
optimize_container: GTM-MMTJJL4
author_avatar: /images/main/avatar2018.jpg
author_about_url: /contact/
permalink: /articles/:categories/:title.html
paginate: 5
paginate_path: "/articles/:num/"

# Dependencies:

plugins:
  - jekyll-redirect-from
  - jekyll-paginate

whitelist:
  - jekyll-redirect-from
  - jekyll-paginate

# Build settings
markdown: kramdown
kramdown:
  input: GFM

sass:
  style: :compressed

# Default github pages settings
safe: true
lsi: false
source: .

# Custom stuff
webfont_version: 1

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: list
    values:
      layout: list
      description: "Regular writing on leading front-end product engineering: development practices, growing teams, and long-term technical strategy."
  - 
    scope:
      path: ""
      type: newsletter
    values:
      layout: newsletter
      description: >-
        Tinned Fruit Missives is a monthly newsletter about web product development and front-end practices.
      twitter_card:
        type: summary
        image: /images/newsletter/tfm-thumb.png
      og_data:
        image: /images/newsletter/tfm-og.png

collections:
  testimonials:
    output: false
  services:
    output: true
  newsletter:
    output: true
  list:
    output: true
  clients:
    output: false
